const {chromium}=require('playwright');
(async()=>{
  const b=await chromium.launch();const p=await b.newPage();
  p.on('pageerror',e=>console.log('ERROR',e.message));
  await p.goto('http://127.0.0.1:8484/login');
  await p.getByLabel('Username',{exact:true}).fill('ui-alpha');
  await p.getByLabel('Password',{exact:true}).fill('synthetic-alpha-password-2026');
  await p.getByRole('button',{name:'Login',exact:true}).click();
  await p.waitForTimeout(3000);
  await p.goto('http://127.0.0.1:8484/admin/onboarding');
  await p.getByRole('button',{name:'Get started',exact:true}).click({timeout:30000});
  await p.waitForTimeout(60000);
  await p.getByRole('combobox').first().click();
  await p.getByRole('option',{name:'Kerala',exact:true}).click();
  await p.getByRole('combobox').nth(1).click();
  await p.getByRole('option',{name:'Ernakulam',exact:true}).click();
  await p.getByRole('button',{name:'Continue',exact:true}).click();
  await p.locator('#fname').fill('Alpha Test Clinic');
  await p.getByRole('combobox').first().click();
  console.log('Facility types:',await p.getByRole('option').allTextContents());
  await p.getByRole('option').first().click();
  await p.locator('#fphone').fill('9999999999');
  await p.locator('#fpin').fill('683101');
  await p.locator('#faddress').fill('Synthetic test address, Aluva');
  await p.getByRole('button',{name:'Create clinic',exact:true}).click();
  await p.waitForTimeout(5000);
  await p.getByRole('button',{name:'General Medicine',exact:true}).click();
  await p.getByRole('button',{name:'Save departments',exact:true}).click();
  await p.waitForTimeout(5000);
  console.log(await p.locator('body').innerText());
  await p.screenshot({path:'dist/onboarding-roles.png',fullPage:true});
  await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
